export const ResumeSchemas = {
  GeneratedResume: {
    type: 'object',
    properties: {
      id: {
        type: 'string',
        format: 'uuid',
      },
      userId: {
        type: 'string',
        format: 'uuid',
      },
      jobDescription: {
        type: 'string',
        example: 'We are looking for a Senior Software Engineer...',
      },
      companyName: {
        type: 'string',
        example: 'Tech Corp',
        nullable: true,
      },
      jobTitle: {
        type: 'string',
        example: 'Senior Software Engineer',
        nullable: true,
      },
      optimizedContent: {
        type: 'object',
        description: 'Structured resume content generated by AI',
      },
      coverLetter: {
        type: 'string',
        nullable: true,
      },
      templateId: {
        type: 'string',
        format: 'uuid',
        nullable: true,
      },
      templateCustomization: {
        type: 'object',
        nullable: true,
      },
      sectionOrder: {
        type: 'array',
        items: {
          type: 'string',
        },
        example: ['summary', 'experience', 'education', 'skills', 'certifications', 'languages'],
      },
      pdfUrl: {
        type: 'string',
        format: 'uri',
        nullable: true,
      },
      status: {
        type: 'string',
        enum: ['DRAFT', 'GENERATED', 'EXPORTED'],
        example: 'GENERATED',
      },
      createdAt: {
        type: 'string',
        format: 'date-time',
      },
      updatedAt: {
        type: 'string',
        format: 'date-time',
      },
    },
  },
  ResumeTemplate: {
    type: 'object',
    properties: {
      id: {
        type: 'string',
        format: 'uuid',
      },
      name: {
        type: 'string',
        example: 'Professional',
      },
      description: {
        type: 'string',
        example: 'Clean, professional template optimized for ATS',
      },
      structure: {
        type: 'object',
        description: 'Template layout and section configuration',
      },
      styling: {
        type: 'object',
        description: 'Template colors, fonts, and styling options',
      },
      previewImage: {
        type: 'string',
        format: 'uri',
        nullable: true,
      },
      category: {
        type: 'string',
        enum: ['PROFESSIONAL', 'MODERN', 'CREATIVE', 'MINIMAL', 'TECHNICAL', 'EXECUTIVE'],
        example: 'PROFESSIONAL',
      },
      isActive: {
        type: 'boolean',
        example: true,
      },
      createdAt: {
        type: 'string',
        format: 'date-time',
      },
    },
  },
};
